import { request } from './api.js';

async function loadSources(){const response=await request('/api/telegram/sources');if(!response.ok)throw new Error(`加载 Scanner 状态失败（HTTP ${response.status}）`);const data=await response.json();if(!Array.isArray(data))throw new Error('Scanner 状态接口返回数据无效');return data;}
function detailTable(headers,rows){const table=document.createElement('table');table.className='admin-table';table.innerHTML=`<thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead>`;const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const value of row){const td=document.createElement('td');td.textContent=String(value??'-');tr.appendChild(td);}body.appendChild(tr);}table.appendChild(body);return table;}
export async function renderScanner(container,section='tasks'){
  container.replaceChildren();const page=document.createElement('div');page.className='admin-page';const title=document.createElement('h1');title.textContent=`扫描器 / ${section==='tasks'?'任务':section==='logs'?'日志':'设置'}`;page.appendChild(title);container.appendChild(page);
  if(section==='tasks')return renderTasks(page);if(section==='logs')return renderLogs(page);if(section==='settings')return renderSettings(page);
}
async function renderTasks(container){const toolbar=document.createElement('div');toolbar.className='toolbar';const refresh=document.createElement('button');refresh.type='button';refresh.textContent='刷新状态';const list=document.createElement('div');list.style.marginTop='12px';toolbar.appendChild(refresh);container.append(toolbar,list);async function load(){refresh.disabled=true;list.textContent='正在加载……';try{const sources=await loadSources();list.replaceChildren();if(!sources.length){list.textContent='暂无已启用 Source。';return;}const wrap=document.createElement('section');wrap.className='panel';wrap.appendChild(detailTable(['Source ID','名称','账号','Chat ID','状态','扫描状态'],sources.map(s=>[s.id,s.name||s.telegram_chat_id,s.account_name,s.telegram_chat_id,s.enabled?'已启用':'已禁用',s.scan_status||'idle'])));list.appendChild(wrap);}catch(error){list.textContent=`加载失败：${error.message}`;}finally{refresh.disabled=false;}}refresh.onclick=load;await load();}
function renderLogs(container){const item=document.createElement('section');item.className='panel';item.appendChild(detailTable(['项目','状态'],[['扫描日志查询 API','未提供'],['当前处理','无法从后端查询']]));const note=document.createElement('p');note.className='meta';note.textContent='当前后端没有 Scanner 日志查询 API，因此不伪造日志数据。';item.appendChild(note);container.appendChild(item);}
function renderSettings(container){const item=document.createElement('section');item.className='panel';item.appendChild(detailTable(['配置项','来源','在线修改'],[['扫描周期','服务器端 SCAN_INTERVAL','不支持']]));const note=document.createElement('p');note.className='meta';note.textContent='当前没有在线修改 API。';item.appendChild(note);container.appendChild(item);}
